#集群名称
cluster.name: es-cluster
#节点名称
node.name: es-master
#绑定host，0.0.0.0代表当前节点的ip
network.host: 0.0.0.0
#设置对外服务的http端口，默认为9200
http.port: 9200
#设置节点间交互的tcp端口，默认是9300
#transport.tcp.port: 9300
#是否支持跨域，默认为false
http.cors.enabled: true
#当设置允许跨域，默认为*,表示支持所有域名，如果我们只是允许某些网站能访问，那么可以使用正则表达式。比如只允许本地地址。/https?:\/\/localhost(:[0-9]+)?/
http.cors.allow-origin: "*"
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: false
#锁定物理内存地址，防止es内存被交换出去
bootstrap.memory_lock: true
#ES8默认开启了 ssl 认证，这里关闭
xpack.security.http.ssl.enabled: false
#不使用密码登录
xpack.security.enabled: false
discovery.seed_hosts: [ "es-master", "es-node1", "es-node2" ]
cluster.initial_master_nodes: [ "es-master", "es-node1", "es-node2" ]
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs